services:
  - type: web
    name: heart-disease-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run heart_disease_app.py --server.port 10000 --server.address 0.0.0.0
